const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  UNAUTHORIZED,
  FORBIDDEN,
  SERVER_ERROR,
  CONFLICT_ERROR,
};
